#!/usr/bin/env bash

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {

    [ $(cat "$bat/status") = Charging ] && echo "" && exit

    if [ "$per" -gt "90" ]; then
        icon="󰁹"
    elif [ "$per" -gt "80" ]; then
        icon="󰂂"
    elif [ "$per" -gt "70" ]; then
        icon="󰂁"
    elif [ "$per" -gt "60" ]; then
        icon="󰂀"
    elif [ "$per" -gt "50" ]; then
        icon="󰁿"
    elif [ "$per" -gt "40" ]; then
        icon="󰁾"
    elif [ "$per" -gt "30" ]; then
        icon="󰁽"
    elif [ "$per" -gt "20" ]; then
        icon="󰁼"
    elif [ "$per" -gt "10" ]; then
        icon="󰁻"
        notify-send -u critical "Battery Low" "Connect Charger"
    elif [ "$per" -gt "0" ]; then
        icon="󰁺"
        notify-send -u critical "Battery Low" "Connect Charger"
    else
        echo 󰂑 && exit
    fi
    echo "$icon"
}

percent() {
    echo $per
}

charge() {
    if cat /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode; then
        sudo tlp fullcharge
    else
        sudo tlp setcharge && exit
    fi
    # echo "${charge-icon}"
}

charge-icon() {
    if cat /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode; then
        echo 󱈑
    else
        echo 󰂄 && exit
    fi
}

power() {
    if sudo tlp-stat -s | grep -q "battery (manual)"; then
        sudo tlp ac
    elif sudo tlp-stat -s | grep -q "AC (manual)"; then
        sudo tlp start
    else
        sudo tlp bat && exit
    fi
}

power-icon() {
    if sudo tlp-stat -s | grep -q "battery (manual)"; then
        echo 󰌪
    elif sudo tlp-stat -s | grep -q "AC (manual)"; then
        echo 󰚥
    else
        echo 󰉂 && exit
    fi
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "power" ] && power && exit
[ "$1" = "charge" ] && charge && exit
[ "$1" = "charge-icon" ] && charge-icon && exit
