#!/usr/bin/env bash

icon() {
    if makoctl mode | grep -q "do-not-disturb"; then
        echo 󰂛
    else
        echo 󰂚
    fi
}

state() {
    if makoctl mode | grep -q "do-not-disturb"; then
        status="DND"
    else
        status="ON"
    fi
    echo "${status}"
}

toggle() {
    if makoctl mode | grep -q "do-not-disturb"; then
        makoctl mode -s default
        # makoctl set-mode default
    else
        makoctl mode -s do-not-disturb
        makoctl set-mode do-not-disturb
    fi
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "state" ] && state && exit
[ "$1" = "toggle" ] && toggle && exit
