#!/bin/sh

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"
    #EWW_BIN="$HOME/.local/bin/eww"

    run() {
        eww -c $HOME/.config/eww open calendar --screen 0
    }

    # Run eww daemon if not running
    if [[ ! $(pidof eww) ]]; then
        eww daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        eww -c $HOME/.config/eww close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "launcher" ]; then
    wofi --show drun -b -I -O -Q -p '>' -m -M fuzzy -i -a
elif [ "$1" = "wifi" ]; then
    alacritty -e nmtui
elif [ "$1" = "audio" ]; then
    pavucontrol
elif [ "$1" = "calendar" ]; then
    calendar
fi
