#!/usr/bin/env bash

notify-send "Getting list of relays..."
# Get a list of available relays and morph it into a nice-looking list
# Only works with countries so far, but adjusting to cities likely not that hard with some sed
relay_list=$(mullvad relay list | grep -E '\([a-z]{2}\)' ) # {2,3} to grab each individual city
# Relay list for invidiual cities can be relatively easily used
# Only everything after a closing parentesis would need to be cut-off

connected=$(mullvad status)
if [[ "$connected" =~ "Connected" ]]; then
	toggle=" 󰒎 Disconnect VPN"
elif [[ "$connected" =~ "Disconnected" ]]; then
	toggle=" 󰒍 Connect VPN"
fi

# Use rofi to select wifi network
chosen_relay=$(echo -e "$toggle\n$relay_list" | uniq -u | wofi --dmenu -O alphabetical -p "Mullvad Relay: ")
# Get name of connection
chosen_id=$(echo "${chosen_relay:(-3):2}" | xargs)

if [ "$chosen_relay" = "" ]; then
	exit
elif [ "$chosen_relay" = "󰒍 Connect VPN" ]; then
	mullvad connect
elif [ "$chosen_relay" = "󰒎 Disconnect VPN" ]; then
	mullvad disconnect
else
	# Message to show when connection is activated successfully
	mullvad relay set location "$chosen_id"
	mullvad connect
	sleep 1
	connected_relay=$(mullvad status)
	success_message="Preferences updated.\n You are now connected to the relay: \n\"${connected_relay:13}\"."
	notify-send "Connection Established" "$success_message"
fi
