# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#83a598" }

# Hovered
hovered         = { fg = "#282828", bg = "#83a598" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b8bb26", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#282828", bg = "#504945" }
tab_inactive = { fg = "#a89984", bg = "#3c3836" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#665c54" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Mode
mode_normal = { fg = "#282828", bg = "#ebdbb2", bold = true }
mode_select = { fg = "#282828", bg = "#b8bb26", bold = true }
mode_unset  = { fg = "#282828", bg = "#d3869b", bold = true }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#504945" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#504945" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#504945" }
active   = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#504945" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#83a598" }
rest            = { fg = "#928374" }
desc            = { fg = "#fe8019" }
separator       = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#fe8019" }
run    = { fg = "#83a598" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#d79921" },

    # Videos
    { mime = "video/*", fg = "#d3869b" },
    { mime = "audio/*", fg = "#689d6a" },

    # Archives
    { mime = "application/zip",             fg = "#fe8019" },
    { mime = "application/gzip",            fg = "#fe8019" },
    { mime = "application/x-tar",           fg = "#fe8019" },
    { mime = "application/x-bzip",          fg = "#fe8019" },
    { mime = "application/x-bzip2",         fg = "#fe8019" },
    { mime = "application/x-7z-compressed", fg = "#fe8019" },
    { mime = "application/x-rar",           fg = "#fe8019" },

    { mime = "application/pdf", fg = "#fe8019" },

    # Fallback
    { name = "*", fg = "#ebdbb2" },
    { name = "*/", fg = "#83a598", bold=true }
]


[icon]

rules = [
	# Programming
	{ name = "*.c"    , text = "" },
	{ name = "*.cpp"  , text = "" },
	{ name = "*.class", text = "" },
	{ name = "*.css"  , text = "" },
	{ name = "*.elm"  , text = "" },
	{ name = "*.fish" , text = "" },
	{ name = "*.go"   , text = "" },
	{ name = "*.h"    , text = "" },
	{ name = "*.hpp"  , text = "" },
	{ name = "*.html" , text = "" },
	{ name = "*.jar"  , text = "" },
	{ name = "*.java" , text = "" },
	{ name = "*.js"   , text = "" },
	{ name = "*.jsx"  , text = "" },
	{ name = "*.lua"  , text = "" },
	{ name = "*.nix"  , text = "" },
	{ name = "*.php"  , text = "" },
	{ name = "*.py"   , text = "" },
	{ name = "*.rb"   , text = "" },
	{ name = "*.rs"   , text = "" },
	{ name = "*.sbt"  , text = "" },
	{ name = "*.scala", text = "" },
	{ name = "*.scss" , text = "" },
	{ name = "*.sh"   , text = "" },
	{ name = "*.swift", text = "" },
	{ name = "*.ts"   , text = "" },
	{ name = "*.tsx"  , text = "" },
	{ name = "*.vim"  , text = "" },
	{ name = "*.vue"  , text = "󰡄" },

	# Text
	{ name = "*.conf", text = "" },
	{ name = "*.ini" , text = "" },
	{ name = "*.bash_history*" , text = "" },
	{ name = "*.json", text = "" },
	{ name = "*.md" ,  text = "" },
	{ name = "*.toml", text = "" },
	{ name = "*.txt",  text = "" },
	{ name = "*.log",  text = "" },
	{ name = "*.yaml", text = "" },
	{ name = "*.yml" , text = "" },

	# Archives
	{ name = "*.7z" , text = "" },
	{ name = "*.bz2", text = "" },
	{ name = "*.gz" , text = "" },
	{ name = "*.rar", text = "" },
	{ name = "*.tar", text = "" },
	{ name = "*.xz" , text = "" },
	{ name = "*.zip", text = "" },

	# Images
	{ name = "*.HEIC", text = "" },
	{ name = "*.avif", text = "" },
	{ name = "*.bmp" , text = "" },
	{ name = "*.gif" , text = "" },
	{ name = "*.ico" , text = "" },
	{ name = "*.jpeg", text = "" },
	{ name = "*.jpg" , text = "" },
	{ name = "*.png" , text = "" },
	{ name = "*.svg" , text = "" },
	{ name = "*.webp", text = "" },

	# Movies
	{ name = "*.avi" , text = "" },
	{ name = "*.mkv" , text = "" },
	{ name = "*.mov" , text = "" },
	{ name = "*.mp4" , text = "" },
	{ name = "*.webm", text = "" },

	# Audio
	{ name = "*.aac" , text = "" },
	{ name = "*.flac", text = "" },
	{ name = "*.m4a" , text = "" },
	{ name = "*.mp3" , text = "" },
	{ name = "*.ogg" , text = "" },
	{ name = "*.wav" , text = "" },

	# Documents
	{ name = "*.doc" , text = "" },
	{ name = "*.doct", text = "" },
	{ name = "*.docx", text = "" },
	{ name = "*.dot" , text = "" },
	{ name = "*.ods" , text = "" },
	{ name = "*.ots" , text = "" },
	{ name = "*.pdf" , text = "" },
	{ name = "*.pom" , text = "" },
	{ name = "*.pot" , text = "" },
	{ name = "*.potx", text = "" },
	{ name = "*.ppm" , text = "" },
	{ name = "*.ppmx", text = "" },
	{ name = "*.pps" , text = "" },
	{ name = "*.ppsx", text = "" },
	{ name = "*.ppt" , text = "" },
	{ name = "*.pptx", text = "" },
	{ name = "*.xlc" , text = "" },
	{ name = "*.xlm" , text = "" },
	{ name = "*.xls" , text = "" },
	{ name = "*.xlsm", text = "" },
	{ name = "*.xlsx", text = "" },
	{ name = "*.xlt" , text = "" },
	{ name = "*.csv" , text = "" },

	# Lockfiles
	{ name = "*.lock", text = "" },

	# Misc
	{ name = "*.bin", text = "" },
	{ name = "*.exe", text = "" },
	{ name = "*.pkg", text = "" },

	# Dotfiles
	{ name = ".DS_Store"     , text = "" },
	{ name = ".bashprofile"  , text = "" },
	{ name = ".bashrc"       , text = "" },
	{ name = ".gitattributes", text = "" },
	{ name = ".gitignore"    , text = "" },
	{ name = ".gitmodules"   , text = "" },
	{ name = ".vimrc"        , text = "" },
	{ name = ".zprofile"     , text = "" },
	{ name = ".zshenv"       , text = "" },
	{ name = ".zshrc"        , text = "" },

	# Named files
	{ name = "COPYING"      , text = "󰿃" },
	{ name = "Containerfile", text = "󰡨" },
	{ name = "Dockerfile"   , text = "󰡨" },
	{ name = "LICENSE"      , text = "󰿃" },

	# Directories
	{ name = ".config/"    , text = "" },
	{ name = ".git/"       , text = "" },
	{ name = "Desktop/"    , text = "" },
	{ name = "Development/", text = "" },
	{ name = "Documents/"  , text = "" },
	{ name = "Downloads/"  , text = "" },
	{ name = "Library/"    , text = "" },
	{ name = "Movies/"     , text = "󰨜" },
	{ name = "Music/"      , text = "" },
	{ name = "Pictures/"   , text = "" },
	{ name = "Public/"     , text = "" },
	{ name = "Videos/"     , text = "󰕧" },

	# Default
	{ name = "*" , text = "" },
	{ name = "*/", text = "", bold = true },
]
# : }}}
